/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { IAddrResolver, IAddrResolverInterface } from "../IAddrResolver";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "node",
        type: "bytes32",
      },
    ],
    name: "addr",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IAddrResolver__factory {
  static readonly abi = _abi;
  static createInterface(): IAddrResolverInterface {
    return new Interface(_abi) as IAddrResolverInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IAddrResolver {
    return new Contract(address, _abi, runner) as unknown as IAddrResolver;
  }
}
