/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { IENSRegistry, IENSRegistryInterface } from "../IENSRegistry";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "node",
        type: "bytes32",
      },
    ],
    name: "resolver",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IENSRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IENSRegistryInterface {
    return new Interface(_abi) as IENSRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IENSRegistry {
    return new Contract(address, _abi, runner) as unknown as IENSRegistry;
  }
}
