/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IAddrResolver__factory } from "./IAddrResolver__factory";
export { IENSRegistry__factory } from "./IENSRegistry__factory";
